voice_group bw_1, 33
    voice_directsound 33, 0, DirectSoundWaveData_naminori_0, 255, 0, 255, 0
    voice_directsound 33, 0, DirectSoundWaveData_naminori_0, 255, 0, 255, 0
    voice_directsound 33, 0, DirectSoundWaveData_naminori_0, 255, 0, 255, 0
    voice_directsound 33, 0, DirectSoundWaveData_naminori_0, 255, 0, 255, 0
    voice_directsound 33, 0, DirectSoundWaveData_naminori_0, 255, 0, 255, 0
    voice_directsound 33, 0, DirectSoundWaveData_naminori_0, 255, 0, 255, 0
    voice_directsound 33, 0, DirectSoundWaveData_naminori_0, 255, 0, 255, 0
    voice_directsound 40, 0, DirectSoundWaveData_naminori_14, 255, 0, 255, 0
    voice_directsound 41, 0, DirectSoundWaveData_naminori_21, 255, 0, 255, 0
    voice_directsound 42, 0, DirectSoundWaveData_naminori_12, 255, 0, 255, 0
    voice_directsound 43, 0, DirectSoundWaveData_naminori_23, 255, 0, 255, 0
    voice_directsound 43, 0, DirectSoundWaveData_naminori_23, 255, 0, 255, 0
    voice_directsound 45, 0, DirectSoundWaveData_naminori_24, 255, 0, 255, 0
    voice_directsound 46, 0, DirectSoundWaveData_naminori_13, 255, 0, 255, 0
    voice_directsound 47, 0, DirectSoundWaveData_naminori_22, 255, 0, 255, 0
    voice_directsound 47, 0, DirectSoundWaveData_naminori_22, 255, 0, 255, 0
    voice_directsound 49, 0, DirectSoundWaveData_naminori_2, 255, 0, 255, 0
    voice_directsound 49, 0, DirectSoundWaveData_naminori_2, 255, 0, 255, 0
    voice_directsound 49, 0, DirectSoundWaveData_naminori_2, 255, 0, 255, 0
    voice_directsound 52, 0, DirectSoundWaveData_naminori_1, 255, 0, 255, 0
    voice_directsound 24, 0, DirectSoundWaveData_bw_cymbal1, 255, 0, 255, 0
    voice_directsound 48, 0, DirectSoundWaveData_bw_crash1, 255, 0, 255, 0
    voice_directsound 26, 0, DirectSoundWaveData_bw_snare1, 255, 0, 255, 0
    voice_directsound 26, 0, DirectSoundWaveData_route6_12, 255, 0, 255, 0



