#ifndef GUARD_CORONATION_VIDEO_H
#define GUARD_CORONATION_VIDEO_H

// Generated by GBA Video Studio — do not edit manually.
// Re-run the encoder to regenerate.

#include "global.h"

// ---------------------------------------------------------------------------
// Video parameters
// ---------------------------------------------------------------------------
#define VIDEO_FRAME_COUNT        427
#define VIDEO_DISPLAY_WIDTH      240
#define VIDEO_DISPLAY_HEIGHT     160
#define VIDEO_TOTAL_BYTES        4253498
#define VIDEO_FPS_RAW            74659  // fps * 10000
#define VIDEO_CODEBOOK_SIZE      192
#define VIDEO_EFFECTIVE_CODEBOOK 254  // 0xFF reserved as marker

// Frame type identifiers
#define VIDEO_FRAME_TYPE_I        0x00
#define VIDEO_FRAME_TYPE_P        0x01
#define VIDEO_COLOR_BLOCK_MARKER  0xFF

// Block geometry (2x2 sub-block, 4x4 macroblock)
#define VIDEO_BLOCK_W             2
#define VIDEO_BLOCK_H             2
#define VIDEO_BYTES_PER_BLOCK     6  // YUV420: 4Y + 1Cb + 1Cr
#define VIDEO_ZONE_HEIGHT         16  // pixel rows per zone

// Motion compensation
#define VIDEO_MOTION_RANGE        7
#define VIDEO_MOTION_BLOCK_SIZE   8

// ---------------------------------------------------------------------------
// Audio parameters
// ---------------------------------------------------------------------------
#define VIDEO_AUDIO_FORMAT       2  // 0=PCM 8-bit, 1=ADPCM 4-bit, 2=no audio

// ---------------------------------------------------------------------------
// Skip key — press this button (or combination) during playback to skip.
// Uses GBA button bitmasks. Set to 0 to disable skipping.
// Override before including this header: #define VIDEO_SKIP_KEY  B_BUTTON
// ---------------------------------------------------------------------------
#ifndef VIDEO_SKIP_KEY
#define VIDEO_SKIP_KEY  A_BUTTON
#endif

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

// Create the video player task. Returns the new task ID.
// Call after ResetTasks() so no other tasks interfere.
u8    CoronationVideoPlayer_Start(void);

// Returns TRUE once playback has finished and the task has destroyed itself.
// Poll this from a watcher task to detect completion.
bool8 CoronationVideoPlayer_IsDone(void);

// Immediately stop playback and restore hardware state.
// Only valid while VideoPlayer_IsDone() == FALSE.
void  CoronationVideoPlayer_ForceStop(void);

#endif // GUARD_VIDEO_H
